import { getSession } from "next-auth/react";
import StartingPageContent from "@/components/starting-page/starting-page";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StartingPageContent />
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });

  if (!session) {
    return {
      redirect: {
        destination: "/auth",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
